// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FolderStats summarizes one folder subtree: the total bytes of its live files
 * and the most recent upload time among them (0 when the subtree has no
 * files). LatestUpload stands in for a modification time until dirents carry
 * one, so renames and moves do not affect it.
 */
export interface FolderStats {
    "id": string;
    "bytes": number;
    "latestUpload": number;
}

export interface GalleryAnchor {
    "start_index": number;
    "cursor": string;
}

export interface GalleryBucket {
    "key": string;
    "start_index": number;
    "count": number;
    "upload_time": number;
}

/**
 * GalleryFolder is one tile in the album grid: a folder that directly holds
 * media, how much of it, and the newest item to show as its cover.
 */
export interface GalleryFolder {
    /**
     * FolderID is the drive folder id, or "" for the drive's own root.
     */
    "folder_id": string;
    "name": string;

    /**
     * ItemCount counts media directly in this folder, never its subfolders.
     */
    "item_count": number;

    /**
     * LatestUploadTime is unix seconds; the grid sorts on it.
     */
    "latest_upload_time": number;

    /**
     * The newest item, which is what the tile shows. CoverRevision addresses
     * the thumbnail; a mismatched revision is refused as stale.
     */
    "cover_msg_id": number;
    "cover_revision": number;
    "cover_name": string;
}

export interface GalleryLocation {
    "generation": string;
    "index": number;
    "cursor": string;
}

export interface GalleryTimeline {
    "channel_id": number;
    "generation": string;
    "total_count": number;
    "page_size": number;
    "buckets": GalleryBucket[] | null;
    "anchors": GalleryAnchor[] | null;
}
