// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FolderStats summarizes one folder subtree: the total bytes of its live files
 * and the most recent upload time among them (0 when the subtree has no
 * files). LatestUpload stands in for a modification time until dirents carry
 * one, so renames and moves do not affect it.
 */
export interface FolderStats {
    "id": string;
    "bytes": number;
    "latestUpload": number;
}
