// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export enum PlaybackStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StatusOpening = "opening",
    StatusPlaying = "playing",
    StatusPaused = "paused",
    StatusBuffering = "buffering",
    StatusEnded = "ended",
    StatusFailed = "failed",
    StatusClosed = "closed",
};

export interface Rect {
    "x": number;
    "y": number;
    "width": number;
    "height": number;
}

/**
 * Track is the small, cross-platform subset of mpv track metadata needed by
 * the player UI. Video tracks are intentionally omitted: aid/sid are the only
 * selectable tracks exposed at this boundary.
 */
export interface Track {
    "id": number;
    "type": TrackType;
    "title": string;
    "language": string;
    "codec": string;
    "selected": boolean;
    "default": boolean;
    "forced": boolean;
}

export enum TrackType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    TrackTypeAudio = "audio",
    TrackTypeSubtitle = "subtitle",
};
