// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface FileMetaData {
    "name": string;
    "size": number;
    "msg_id": number;
    "parent_id": string;
    "upload_time": number;
    "uploader_id": number;
    "encrypted"?: boolean;
    "plaintext_size"?: number;
}

export interface FileSystem {
    "folders": Folder[] | null;
    "files": FileMetaData[] | null;
}

export interface Folder {
    "name": string;
    "id": string;
    "parent_id": string;
}

export interface SearchResult {
    "type": string;
    "id": string;
    "name": string;
    "parent_id": string;
    "size": number;
    "upload_time": number;
    "uploader_id": number;
    "encrypted"?: boolean;
    "plaintext_size"?: number;
    "path": string;
}
