// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface OpenResult {
    "base_url": string;
    "token": string;
    "channel_id": number;
}
