// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface State {
    "running": boolean;
    "channel_id": number;
    "completed": number;
    "skipped": number;
    "total": number;
    "bytes_total": number;
    "bytes_done": number;
    "error": string;
}
