// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as backend$0 from "./backend/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as galleryimage$0 from "./backend/galleryimage/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as projection$0 from "./backend/projection/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as file$0 from "./backend/services/file/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ActiveChannelID(): $CancellablePromise<number> {
    return $Call.ByID(915599723);
}

export function AddPhotoBackupFolder(): $CancellablePromise<$models.PhotoBackupSource> {
    return $Call.ByID(700615070);
}

/**
 * CancelDownload cancels the active download.
 */
export function CancelDownload(): $CancellablePromise<void> {
    return $Call.ByID(2532515671);
}

/**
 * CancelUpload cancels the in-flight upload or import: in-flight sends abort and
 * the rest are skipped. The frontend marks the affected transfers canceled.
 */
export function CancelUpload(): $CancellablePromise<void> {
    return $Call.ByID(409390550);
}

/**
 * CancelUploadByID cancels one file of the running batch. Both cancels exist
 * because uploads run several at a time: a transfer row's × stops that one
 * file, while CancelUpload above is the deliberate "stop everything".
 */
export function CancelUploadByID(uploadID: number): $CancellablePromise<void> {
    return $Call.ByID(2968075794, uploadID);
}

export function CheckLoginStatus(): $CancellablePromise<boolean> {
    return $Call.ByID(1827168990);
}

export function CheckSystemStatus(): $CancellablePromise<string> {
    return $Call.ByID(586870272);
}

export function ClearGalleryCache(): $CancellablePromise<$models.GalleryStorage> {
    return $Call.ByID(2783044110);
}

export function CloseGalleryImages(token: string): $CancellablePromise<void> {
    return $Call.ByID(2992155069, token);
}

export function CreateFolder(foldername: string, parentID: string): $CancellablePromise<backend$0.Folder> {
    return $Call.ByID(1403526973, foldername, parentID);
}

export function DeleteFile(msgID: number): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(2962294020, msgID);
}

export function DeleteFolder(folderID: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(127207050, folderID);
}

/**
 * DownloadFile downloads from the explicitly selected drive. The channel is an
 * argument rather than a late ActiveChannelID lookup because a queued frontend
 * transfer may begin after the user has switched drives.
 */
export function DownloadFile(channelID: number, msgID: number, TgMsgID: number, requestID: string): $CancellablePromise<$models.DownloadResult> {
    return $Call.ByID(764734343, channelID, msgID, TgMsgID, requestID);
}

/**
 * DownloadFolder restores the selected projected folder beneath a destination
 * parent chosen once by the user. It shares the serialized/cancellable download
 * slot with single-file downloads, so the existing CancelDownload action stops
 * either transfer type.
 */
export function DownloadFolder(channelID: number, folderID: string, requestID: string): $CancellablePromise<$models.DownloadResult> {
    return $Call.ByID(794478145, channelID, folderID, requestID);
}

export function EnqueuePhotoBackupAssets(sourceID: string, values: $models.PhotoBackupAsset[] | null): $CancellablePromise<number> {
    return $Call.ByID(2612336532, sourceID, values);
}

export function GetAllFsMsgIDs(): $CancellablePromise<number[] | null> {
    return $Call.ByID(2840193812);
}

export function GetFileList(): $CancellablePromise<$models.TDriveFile[] | null> {
    return $Call.ByID(1200732269);
}

export function GetFolderContents(parentID: string): $CancellablePromise<backend$0.FileSystem> {
    return $Call.ByID(3439576765, parentID);
}

export function GetFolderSize(folderID: string): $CancellablePromise<number> {
    return $Call.ByID(1980724058, folderID);
}

export function GetFolderStats(parentID: string): $CancellablePromise<projection$0.FolderStats[] | null> {
    return $Call.ByID(654620998, parentID);
}

export function GetGalleryStorage(): $CancellablePromise<$models.GalleryStorage> {
    return $Call.ByID(940237792);
}

export function GetMediaNeighbors(msgID: number, before: number, after: number, generation: string): $CancellablePromise<$models.GalleryPage> {
    return $Call.ByID(2332667564, msgID, before, after, generation);
}

/**
 * GetMediaTimeline returns only compact layout metadata and sparse page keys.
 * A cursor is tied to the account database, active drive, and projection epoch.
 */
export function GetMediaTimeline(): $CancellablePromise<projection$0.GalleryTimeline> {
    return $Call.ByID(1288157298);
}

export function GetMediaTimelineAnchors(generation: string): $CancellablePromise<projection$0.GalleryTimeline> {
    return $Call.ByID(566606144, generation);
}

export function GetMediaTimelineSummary(): $CancellablePromise<projection$0.GalleryTimeline> {
    return $Call.ByID(3363396734);
}

export function GetPhotoBackupState(): $CancellablePromise<$models.PhotoBackupState> {
    return $Call.ByID(2538605868);
}

export function GetStorageUsed(): $CancellablePromise<number> {
    return $Call.ByID(2694300657);
}

/**
 * ImportPaths recreates the folder structure of the selected paths under
 * parentID and uploads their files. Archives are extracted when extractArchives
 * is set, otherwise uploaded as-is. Progress flows through aggregate import_*
 * events.
 */
export function ImportPaths(paths: string[] | null, parentID: string, encrypt: boolean, extractArchives: boolean): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(4265040680, paths, parentID, encrypt, extractArchives);
}

export function ListMediaPage(cursor: string, limit: number): $CancellablePromise<$models.GalleryPage> {
    return $Call.ByID(836790156, cursor, limit);
}

export function LocateMedia(msgID: number, generation: string): $CancellablePromise<projection$0.GalleryLocation> {
    return $Call.ByID(3544189497, msgID, generation);
}

export function LoginPhoneNumber(phoneNumber: string): $CancellablePromise<void> {
    return $Call.ByID(2884866391, phoneNumber);
}

/**
 * Logout signs the user out of TDrive.
 * 
 * Soft mode drops only the local gotd session token, so the same Telegram
 * account can re-login quickly without re-projecting their drives. The
 * session stays valid server-side until Telegram itself expires it.
 * 
 * Full mode revokes the session on Telegram's side via auth.logOut and then
 * deletes all user-scoped files on disk (session, personal channel id,
 * SQLite cache, API credentials).
 * 
 * In both cases the app quits at the end. We rely on the next launch to
 * rebuild syncEngine, backfillRunner, and the DB handle from a clean slate
 * instead of tearing them down mid-process while goroutines may still be
 * touching backend.DB.
 */
export function Logout(mode: string): $CancellablePromise<void> {
    return $Call.ByID(1110373539, mode);
}

/**
 * Me resolves the logged-in Telegram user and a small base64-encoded
 * avatar photo. The result is cached by the user service for the lifetime
 * of the process; logout clears it.
 */
export function Me(): $CancellablePromise<$models.SelfUser> {
    return $Call.ByID(809520895);
}

/**
 * MountDrive attaches the active drive without changing it. The controller
 * pins this immutable drive record until the user disconnects it.
 */
export function MountDrive(): $CancellablePromise<$models.MountResult> {
    return $Call.ByID(728953670);
}

/**
 * MountDrives attaches an explicit selection inside one TDrive volume. The
 * client supplies IDs only; titles, kinds, and encryption state are resolved
 * from the authoritative local projection before the controller is called.
 */
export function MountDrives(channelIDs: number[] | null): $CancellablePromise<$models.MountResult> {
    return $Call.ByID(2599738479, channelIDs);
}

export function MountStatus(): $CancellablePromise<$models.MountView> {
    return $Call.ByID(1308648460);
}

export function MoveFile(msgID: number, newParentID: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(774099370, msgID, newParentID);
}

export function MoveFolder(folderID: string, newParentID: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(3833907176, folderID, newParentID);
}

export function MsgToTdriveSystem(msgID: number, name: string, size: number, parentID: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(2126330906, msgID, name, size, parentID);
}

/**
 * MyUserID returns the logged-in Telegram user id (cached after first
 * resolution). The frontend uses it to gate owner-only actions on shared
 * drives. Returns an error if Telegram resolution fails — caller should
 * default-deny the gated actions in that case.
 */
export function MyUserID(): $CancellablePromise<number> {
    return $Call.ByID(1596339941);
}

/**
 * OpenGalleryImages creates one capability for a gallery and its viewer. The
 * expected channel prevents a late bridge response from opening a new drive's
 * images under an old UI. Individual binary requests carry their own cancel.
 */
export function OpenGalleryImages(channelID: number): $CancellablePromise<galleryimage$0.OpenResult> {
    return $Call.ByID(2496003119, channelID);
}

export function OpenMountedDrive(): $CancellablePromise<void> {
    return $Call.ByID(4232063021);
}

export function PausePhotoBackup(): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(4020238801);
}

/**
 * PlanImport scans the selected paths and returns the counts shown in the
 * import dialog (files, folders, total size, archives, oversize-skipped). It
 * mutates nothing.
 */
export function PlanImport(paths: string[] | null, encrypt: boolean, extractArchives: boolean): $CancellablePromise<file$0.ImportPlan> {
    return $Call.ByID(1600788103, paths, encrypt, extractArchives);
}

export function PreviewFile(msgID: number): $CancellablePromise<$models.PreviewResult> {
    return $Call.ByID(4109354993, msgID);
}

export function PreviewThumbnail(msgID: number): $CancellablePromise<$models.PreviewResult> {
    return $Call.ByID(3653345973, msgID);
}

/**
 * RebuildProjection wipes and replays the local projection for a channel
 * from the channel's replay_log. Hidden Wails method for debug/recovery.
 */
export function RebuildProjection(channelID: number): $CancellablePromise<void> {
    return $Call.ByID(1334807909, channelID);
}

export function RemovePhotoBackupSource(id: string): $CancellablePromise<void> {
    return $Call.ByID(560528492, id);
}

export function RenameFile(msgID: number, newName: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(1151698069, msgID, newName);
}

export function RenameFolder(folderID: string, newName: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(3733990943, folderID, newName);
}

export function ResolvePhotoBackupResource(token: string, path: string, errorMessage: string): $CancellablePromise<void> {
    return $Call.ByID(3713811339, token, path, errorMessage);
}

/**
 * ResolveUsernames maps Telegram user IDs to display names. Used by the
 * frontend uploader-chip cache.
 */
export function ResolveUsernames(userIDs: number[] | null): $CancellablePromise<{ [_ in string]?: string } | null> {
    return $Call.ByID(4195625464, userIDs);
}

export function ResumePhotoBackup(): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(1448669500);
}

export function RetryPhotoBackup(): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(2648028709);
}

/**
 * The backup controls answer with the common operation envelope so the
 * frontend can branch on a stable code — a locked vault opens the password
 * prompt, anything else is shown in the backend's own words — rather than
 * sniffing display text out of a wrapped Go error.
 */
export function RunPhotoBackup(): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(424636428);
}

export function SavePhotoBackupSettings(value: $models.PhotoBackupSettings): $CancellablePromise<$models.PhotoBackupState> {
    return $Call.ByID(1900832239, value);
}

export function SaveSetup(apiId: number, apiHash: string): $CancellablePromise<string> {
    return $Call.ByID(1847944557, apiId, apiHash);
}

export function Search(query: string, limit: number): $CancellablePromise<backend$0.SearchResult[] | null> {
    return $Call.ByID(3097496321, query, limit);
}

export function SelectFiles(): $CancellablePromise<string[] | null> {
    return $Call.ByID(937743440);
}

/**
 * SelectFolder opens a directory picker and returns the chosen folder path
 * (empty if the user cancels). Folder import walks it on the Go side.
 */
export function SelectFolder(): $CancellablePromise<string> {
    return $Call.ByID(237181597);
}

export function SendHint(hint: string): $CancellablePromise<void> {
    return $Call.ByID(1764638182, hint);
}

export function SetActiveChannel(channelID: number): $CancellablePromise<void> {
    return $Call.ByID(409139060, channelID);
}

/**
 * SetFileDropEnabled toggles whether the native OS file-drop handler (wired
 * up once in main.go against the window) forwards drops to the frontend. The
 * frontend turns it off for the duration of an internal drag-to-move: on
 * macOS the webview's native drop destination otherwise intercepts the
 * in-app HTML5 drag, which breaks the move and pops the upload dialog.
 */
export function SetFileDropEnabled(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(2923268397, enabled);
}

/**
 * SetPhotoBackupBackgroundLease records a lease only after the native host has
 * acquired its execution grant. Repeated calls cannot extend Android's
 * cumulative dataSync budget.
 */
export function SetPhotoBackupBackgroundLease(active: boolean): $CancellablePromise<void> {
    return $Call.ByID(418947735, active);
}

export function SetPhotoBackupPolicy(policy: $models.PhotoBackupPolicy): $CancellablePromise<void> {
    return $Call.ByID(1872922881, policy);
}

/**
 * ShareFile opens the platform share sheet for a file TDrive wrote itself.
 * Anything outside the folders it owns is refused so the webview cannot hand
 * arbitrary files to other apps. Desktop reports unsupported.
 */
export function ShareFile(path: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(3239681846, path);
}

export function SubmitCode(code: string): $CancellablePromise<void> {
    return $Call.ByID(2820917964, code);
}

export function SubmitPassword(password: string): $CancellablePromise<void> {
    return $Call.ByID(718394480, password);
}

/**
 * SyncChannel triggers an incremental sync for the given channel. Wails-bound
 * for the future "Refresh" UI button and for debug.
 */
export function SyncChannel(channelID: number): $CancellablePromise<void> {
    return $Call.ByID(3481222021, channelID);
}

export function UnmountDrive(): $CancellablePromise<$models.MountView> {
    return $Call.ByID(3796068953);
}

export function UploadToDriveFS(filePaths: string[] | null, parentIDs: string[] | null, encrypt: boolean): $CancellablePromise<$models.UploadResult> {
    return $Call.ByID(1816080344, filePaths, parentIDs, encrypt);
}

export function UpsertPhotoBackupSource(value: $models.PhotoBackupSource): $CancellablePromise<$models.PhotoBackupSource> {
    return $Call.ByID(713485105, value);
}
