// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DeviceService exposes the OS-level affordances the webview cannot reach on
 * its own: haptics, screenshot protection, keyboard-visibility reporting,
 * immersive mode, and the screen edges the system reserves for its own chrome.
 * 
 * They belong together because of the one property no other binding shares:
 * none of them touch the engine, the vault or a drive. That is what lets them
 * answer while the backend is still starting, or after it has failed to start
 * at all. Leaving them on App would have tied the frontend's earliest calls --
 * safe-area insets are needed before the first paint -- to whether the Telegram
 * session came up, and a phone would render its chrome under the status bar
 * whenever login was slow.
 * 
 * application.Mobile dispatches to the iOS or Android manager and to a no-op
 * stub on desktop, so every method here is safe to call from shared frontend
 * code and the whole type compiles unconditionally on all five platforms.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Haptic plays a semantic feedback pattern: a light impact for a long press or
 * an armed pull, "selection" for a changed sort or filter, and success/warning/
 * error only at a real outcome. The OS maps these to its own generator, so a
 * user who has turned system haptics off feels nothing, as they asked.
 */
export function Haptic(kind: string): $CancellablePromise<void> {
    return $Call.ByID(342438060, kind);
}

/**
 * SafeAreaInsets reports those reserved edges. The frontend asks for them
 * because CSS cannot see all of them: Android's WebView fills
 * env(safe-area-inset-top) but leaves the bottom gesture area at zero.
 */
export function SafeAreaInsets(): $CancellablePromise<$models.SafeAreaInsets> {
    return $Call.ByID(1341911161);
}

/**
 * SetImmersive hides the system bars for a full-screen surface, or gives them
 * back. The video player is the only caller: everywhere else the bars belong on
 * screen, and hiding them would just make the app harder to leave.
 * 
 * It is not only about looking tidy. An app targeting SDK 35 is laid out edge
 * to edge on Android 15 whether it asks or not, and the system paints a
 * translucent scrim behind three-button navigation so the buttons stay legible
 * over whatever is beneath them. That scrim lands on top of the picture as a
 * grey band down one edge, and the API that used to switch it off --
 * setNavigationBarContrastEnforced -- does nothing at this target. The bar
 * itself can still be hidden, which removes the scrim with it.
 * 
 * iOS has no navigation bar to hide, so there the payload only takes the status
 * bar, which is what a full-screen player wants anyway.
 */
export function SetImmersive(on: boolean): $CancellablePromise<void> {
    return $Call.ByID(257453220, on);
}

/**
 * SetKeyboardWatch starts or stops "common:keyboard" {visible,height} events.
 * The frontend prefers visualViewport where it exists and falls back to these,
 * which is the only source Android's WebView reports reliably.
 */
export function SetKeyboardWatch(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(3988562811, enabled);
}

/**
 * SetScreenProtect asks the OS to keep the app's contents out of screenshots
 * and the app switcher while the vault is locked or privacy is raised.
 * 
 * The two platforms do NOT deliver the same thing. Android sets FLAG_SECURE,
 * which really does blank screenshots, screen recording and the switcher
 * thumbnail. iOS cannot block any of that: the same call only starts
 * *detection*, reported back as a "common:screenCapture" event. Hiding the iOS
 * switcher preview needs a native overlay on resign-active that this host does
 * not have yet, so on iOS treat this as telemetry, not protection.
 */
export function SetScreenProtect(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(1083386308, enabled);
}
