// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DriveService owns the set of drives themselves: which ones this client knows
 * about, how a shared one is created, joined, approved or left, and how the
 * personal one is first chosen or made.
 * 
 * The line it draws is between a drive and its contents. Everything here
 * changes *which* drives exist or who may reach them; nothing here reads or
 * writes a file inside one. That matters because these are the only calls that
 * can run before a drive is selected at all -- a fresh install has no personal
 * channel, and a user recovering an old one has no projection yet -- so they
 * must not share a type with methods that assume an active drive is already
 * scoped. They are also the only calls that go to Telegram's channel and invite
 * APIs rather than to the local projection, which is why they fail in ways
 * (approval pending, admin-only, flood wait) no file operation ever produces.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ApproveJoinRequest(channelID: number, userID: number): $CancellablePromise<void> {
    return $Call.ByID(2019042839, channelID, userID);
}

/**
 * CheckPendingJoin checks whether a prior approval-required request has now
 * become a membership. Users call this manually from the sidebar; no realtime
 * Telegram update stream is required for v1.
 */
export function CheckPendingJoin(inviteHash: string): $CancellablePromise<$models.JoinDriveResult> {
    return $Call.ByID(2094375382, inviteHash);
}

export function CreatePersonalDrive(): $CancellablePromise<void> {
    return $Call.ByID(1209752899);
}

/**
 * CreateSharedDrive creates a Telegram megagroup, exports an invite link,
 * inserts the channel row, and switches the active drive to it.
 * 
 * Returns the new ChannelInfo with the invite link populated.
 */
export function CreateSharedDrive(title: string, requireApproval: boolean): $CancellablePromise<$models.ChannelInfo> {
    return $Call.ByID(3280234352, title, requireApproval);
}

/**
 * DiscoverPersonalDrives lists the broadcast channels the user created so an
 * existing drive can be recovered. Read-only.
 */
export function DiscoverPersonalDrives(): $CancellablePromise<$models.PersonalDriveCandidate[] | null> {
    return $Call.ByID(2043630943);
}

/**
 * GetApprovalInviteLink fetches an invite link where Telegram requires an
 * admin to approve each requester before they become a member.
 */
export function GetApprovalInviteLink(channelID: number): $CancellablePromise<string> {
    return $Call.ByID(2139346013, channelID);
}

/**
 * GetInviteLink fetches a fresh link from Telegram and caches it. Admin-
 * only on the Telegram side; non-admin members will get an error from
 * MessagesExportChatInvite. (Step 4 doesn't gate this client-side; we
 * surface whatever Telegram returns.)
 */
export function GetInviteLink(channelID: number): $CancellablePromise<string> {
    return $Call.ByID(2291750174, channelID);
}

/**
 * JoinSharedDrive imports an invite link. Immediate links return a joined
 * channel. Approval-required links send a Telegram join request and return a
 * durable pending record that can be checked later.
 */
export function JoinSharedDrive(inviteLink: string): $CancellablePromise<$models.JoinDriveResult> {
    return $Call.ByID(52922340, inviteLink);
}

/**
 * LeaveSharedDrive leaves the Telegram channel and drops every local row
 * scoped to it. If the active drive was this one, switches active to the
 * personal drive.
 */
export function LeaveSharedDrive(channelID: number): $CancellablePromise<void> {
    return $Call.ByID(3257238219, channelID);
}

/**
 * ListChannels returns every drive known to this client (personal first,
 * then shared in joined-at order). Used to render the sidebar.
 */
export function ListChannels(): $CancellablePromise<$models.ChannelInfo[] | null> {
    return $Call.ByID(1594083029);
}

/**
 * ListJoinRequests lists Telegram users waiting for admin approval on a drive.
 */
export function ListJoinRequests(channelID: number): $CancellablePromise<$models.JoinRequestInfo[] | null> {
    return $Call.ByID(937442775, channelID);
}

/**
 * ListPendingJoins returns approval-required joins this client is waiting on.
 */
export function ListPendingJoins(): $CancellablePromise<$models.PendingJoinInfo[] | null> {
    return $Call.ByID(4115008349);
}

/**
 * PreparePersonalDrive activates the saved personal drive, or reports that
 * the user has to choose one. It never contacts Telegram.
 */
export function PreparePersonalDrive(): $CancellablePromise<$models.PersonalDriveSetupState> {
    return $Call.ByID(1860739232);
}

export function RejectJoinRequest(channelID: number, userID: number): $CancellablePromise<void> {
    return $Call.ByID(2863888627, channelID, userID);
}

/**
 * RemovePendingJoin forgets a local pending request. It does not revoke the
 * Telegram-side request; only a drive admin can reject it.
 */
export function RemovePendingJoin(inviteHash: string): $CancellablePromise<void> {
    return $Call.ByID(1400756080, inviteHash);
}

export function SelectPersonalDrive(channelID: string): $CancellablePromise<void> {
    return $Call.ByID(3256489003, channelID);
}
