// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * EncryptionService owns the vault password: what the frontend may know about
 * it, how it is first created, how it is unlocked for the session, and how it
 * is changed.
 * 
 * These four are grouped because each one moves the master key in or out of
 * process memory, and every one of them must therefore hold the mount lifecycle
 * gate for the whole operation. Splitting them across types would invite a
 * fifth key-touching method that forgets the gate, and a key that changes while
 * a drive is mounted leaves the filesystem serving bytes it can no longer
 * decrypt. Everything that only *reads* an already-unlocked key -- uploads,
 * previews, the mount itself -- stays out of here on purpose.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ChangeEncryptionPassword verifies the current password, then re-wraps
 * the same master key with the new password. Existing encrypted files stay
 * decryptable; file contents are not re-encrypted.
 */
export function ChangeEncryptionPassword(currentPassword: string, newPassword: string, hint: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(616153624, currentPassword, newPassword, hint);
}

/**
 * CreateEncryptionPassword creates the user's first encryption password.
 * It stores a random master key wrapped under the password and an optional
 * plaintext hint. It refuses to overwrite an existing password.
 */
export function CreateEncryptionPassword(password: string, hint: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(721726100, password, hint);
}

/**
 * EncryptionStatus reports whether the user has set an encryption
 * password, and whether that password has already been accepted for the
 * current app session.
 */
export function EncryptionStatus(): $CancellablePromise<$models.EncryptionStatus> {
    return $Call.ByID(2002790111);
}

/**
 * UseEncryptionPassword verifies an existing encryption password and keeps
 * the master key in memory for the rest of the app session.
 */
export function UseEncryptionPassword(password: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(1896641839, password);
}
