// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MediaService owns everything that turns a file in a drive into something the
 * user can look at: the media library listing, thumbnails, the tokenized
 * loopback streams the webview plays from, and the out-of-webview native
 * players that take over when the webview cannot decode a file.
 * 
 * Those last two are why this is one service and not two. A native player and a
 * loopback session are halves of the same resource: the player reads bytes
 * through the session, and closing either one without the other leaks a range
 * reader, an mpv process, or both. Keeping them on one type means the pairing
 * is enforced by a single mutex-guarded table rather than by two services
 * remembering to call each other in the right order.
 * 
 * It also means only this service ever has to be asked to shut players down --
 * which the updater and the vault lock both need, and both do through the
 * narrow nativeMediaCloser rather than by reaching in here.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as backend$0 from "./backend/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as media$0 from "./backend/media/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as nativeplayer$0 from "./backend/nativeplayer/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AttachNativeMedia attaches the native player to an existing loopback media
 * session. It is used when the embedded webview cannot decode a file, allowing
 * the fallback to keep the same token and range cache. Ownership of the media
 * session remains with the original opener, including on attachment failure.
 */
export function AttachNativeMedia(token: string, rect: nativeplayer$0.Rect): $CancellablePromise<$models.NativeMediaResult> {
    return $Call.ByID(4266978577, token, rect);
}

export function CloseMedia(token: string): $CancellablePromise<void> {
    return $Call.ByID(4150155781, token);
}

export function CloseNativeMedia(token: string): $CancellablePromise<void> {
    return $Call.ByID(2957228052, token);
}

export function GetMediaStats(token: string): $CancellablePromise<media$0.MediaStats> {
    return $Call.ByID(3209083096, token);
}

/**
 * HideNativeSeekThumbnail hides the seek-preview overlay for the session.
 */
export function HideNativeSeekThumbnail(token: string): $CancellablePromise<void> {
    return $Call.ByID(512311778, token);
}

/**
 * ListMedia is the legacy bulk API. The gallery uses GetMediaTimeline and
 * ListMediaPage so metadata memory stays bounded as the library grows.
 */
export function ListMedia(): $CancellablePromise<backend$0.FileMetaData[] | null> {
    return $Call.ByID(3393040959);
}

/**
 * MoveNativeSeekThumbnail moves the already-painted seek-preview overlay without
 * re-uploading or re-decoding the frame. Windows calls this on every scrub move;
 * keeping it separate from ShowNativeSeekThumbnail avoids doing JPEG decode and
 * GDI bitmap upload work just to follow the cursor.
 */
export function MoveNativeSeekThumbnail(token: string, rect: nativeplayer$0.Rect): $CancellablePromise<void> {
    return $Call.ByID(2479182657, token, rect);
}

export function NativeMediaCommand(token: string, command: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(1926610811, token, command);
}

/**
 * OpenMedia creates a short-lived, tokenized loopback URL for a plain media
 * file in the active drive. The frontend player must call CloseMedia when the
 * preview closes so the underlying range reader and cache are released.
 */
export function OpenMedia(msgID: number): $CancellablePromise<media$0.OpenResult> {
    return $Call.ByID(280923895, msgID);
}

/**
 * OpenNativeMedia opens the same tokenized loopback stream as OpenMedia, then
 * hands it to the native player. The returned token owns both resources.
 */
export function OpenNativeMedia(msgID: number, rect: nativeplayer$0.Rect): $CancellablePromise<$models.NativeMediaResult> {
    return $Call.ByID(3935000446, msgID, rect);
}

/**
 * OpenStream creates a tokenized loopback byte stream for an in-app file
 * opener. Unlike OpenMedia, it is not video-only; callers choose the viewer
 * from the returned stream kind and must still call CloseMedia on close.
 */
export function OpenStream(msgID: number): $CancellablePromise<media$0.OpenResult> {
    return $Call.ByID(3394485217, msgID);
}

export function ResizeNativeMedia(token: string, rect: nativeplayer$0.Rect): $CancellablePromise<void> {
    return $Call.ByID(3920426918, token, rect);
}

/**
 * ShowNativeSeekThumbnail paints a seek-preview thumbnail over the native video.
 * imageBase64 is the raw base64 of the JPEG frame the backend's own thumbnailer
 * produced and the frontend already holds; rect is the desired preview box in
 * CSS pixels. It is only meaningful on the Windows fallback (where HTML can't
 * draw over the video) and is a no-op on platforms without an overlay.
 */
export function ShowNativeSeekThumbnail(token: string, imageBase64: string, rect: nativeplayer$0.Rect): $CancellablePromise<void> {
    return $Call.ByID(893096185, token, imageBase64, rect);
}

/**
 * Thumbnail is the legacy base64 wrapper around the bounded rendition path.
 * Cache misses fetch an existing small derivative, never the original photo.
 */
export function Thumbnail(msgID: number): $CancellablePromise<$models.PreviewPayload> {
    return $Call.ByID(1935725111, msgID);
}

export function UpdateMediaPlayback(update: media$0.PlaybackUpdate): $CancellablePromise<void> {
    return $Call.ByID(4050638745, update);
}
