// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as backend$0 from "./backend/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as media$0 from "./backend/media/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as nativeplayer$0 from "./backend/nativeplayer/models.js";

/**
 * AppVersionInfo describes the running build for the About/Updates panel.
 */
export interface AppVersionInfo {
    "version": string;
    "os": string;
    "arch": string;
    "dev_build": boolean;
}

/**
 * ChannelInfo is the Wails-bound DTO for a drive listed in the sidebar.
 */
export interface ChannelInfo {
    "id": number;
    "title": string;

    /**
     * "personal" | "shared"
     */
    "kind": string;
    "is_active": boolean;
    "invite_link"?: string;
}

/**
 * DownloadResult adds the chosen destination to the common operation envelope.
 */
export interface DownloadResult {
    "result": OperationResult;
    "saved_path": string;
}

/**
 * EncryptionStatus is the snapshot the frontend uses for per-upload prompts
 * and for unlocking an encrypted personal-drive mount. Mounted writes always
 * follow the drive policy; they never expose a per-file encryption choice.
 */
export interface EncryptionStatus {
    /**
     * a personal channel is known
     */
    "available": boolean;

    /**
     * user has created an encryption password
     */
    "password_set": boolean;

    /**
     * master key is in process memory
     */
    "password_remembered": boolean;

    /**
     * optional plaintext password hint
     */
    "hint": string;
}

/**
 * GalleryItem keeps existing file wire fields while adding immutable content
 * identity. Pixel caches must use content identity, never a filename alone.
 */
export interface GalleryItem {
    "name": string;
    "size": number;
    "msg_id": number;
    "parent_id": string;
    "upload_time": number;
    "uploader_id": number;
    "encrypted"?: boolean;
    "plaintext_size"?: number;
    "content_msg_id": number;
    "content_hash": string;
    "revision": number;
}

export interface GalleryPage {
    "generation": string;
    "start_index": number;
    "anchor_offset": number;
    "items": GalleryItem[] | null;
    "next_cursor": string;
}

/**
 * GalleryStorage separates disposable media from the durable local catalog.
 * Saved downloads are user files and are never included in cache cleanup.
 */
export interface GalleryStorage {
    "cache_bytes": number;
    "cache_limit": number;
    "cache_entries": number;
    "catalog_bytes": number;
}

/**
 * JoinDriveResult distinguishes instant joins from approval-required requests.
 */
export interface JoinDriveResult {
    /**
     * "joined" | "pending"
     */
    "status": string;
    "channel"?: ChannelInfo | null;
    "pending"?: PendingJoinInfo | null;
}

/**
 * JoinRequestInfo is shown to admins for approval-required invite links.
 */
export interface JoinRequestInfo {
    "user_id": number;
    "display_name": string;
    "username"?: string;
    "requested_at": number;
    "about"?: string;
}

export interface MountDriveView {
    "id"?: number;
    "title"?: string;
    "kind"?: string;
}

/**
 * MountResult adds capability-free mount state to the common operation envelope.
 */
export interface MountResult {
    "result": OperationResult;
    "mount": MountView;
}

/**
 * MountView is the capability-free mount state exposed to the webview. The
 * private WebDAV endpoint never crosses the Go/Wails boundary.
 */
export interface MountView {
    "phase": string;
    "mounted": boolean;
    "mode"?: string;
    "write_state"?: string;
    "accepting_writes"?: boolean;
    "active_writes"?: number;
    "label"?: string;
    "location"?: string;
    "error"?: string;
    "drive"?: MountDriveView;
    "windows_drive"?: string;
}

export interface NativeMediaRange {
    "start": number;
    "end": number;
}

export interface NativeMediaResult {
    "token": string;
    "name": string;
    "thumbnail_url": string;
    "html_controls": boolean;
    "presentation": string;
    "initial_state"?: NativeMediaState | null;
    "info": media$0.LogicalFile;
}

export interface NativeMediaState {
    "token"?: string;
    "sequence": number;
    "status": nativeplayer$0.PlaybackStatus;
    "error"?: string;
    "eof": boolean;
    "paused": boolean;
    "current_time": number;
    "duration": number;
    "buffered": NativeMediaRange[] | null;
    "volume": number;
    "muted": boolean;
    "rate": number;
    "loading": boolean;
    "tracks": nativeplayer$0.Track[] | null;
}

/**
 * OperationError keeps a stable code separate from user-facing detail.
 * cause is retained for native callers and deliberately omitted from JSON.
 */
export interface OperationError {
    "code": OperationErrorCode;
    "message": string;
}

/**
 * Operation error codes are stable control-plane values exposed over Wails.
 * The accompanying message is display text and must never be used for branching.
 */
export type OperationErrorCode = string;

/**
 * OperationResult is the common Wails operation envelope.
 */
export interface OperationResult {
    "ok": boolean;
    "error"?: OperationError | null;
}

/**
 * PendingJoinInfo is a local record for approval-required invite links where
 * the current Telegram account has requested access but is not a member yet.
 */
export interface PendingJoinInfo {
    "invite_hash": string;
    "invite_link": string;
    "title": string;
    "requested_at": number;
    "last_checked_at": number;
    "status": string;
    "last_error": string;
}

/**
 * PersonalDriveCandidate is a channel the user may recover as their drive.
 * The ID is a decimal string: Telegram IDs exceed JavaScript's safe integer
 * range. Access hashes stay backend-only.
 */
export interface PersonalDriveCandidate {
    "id": string;
    "title": string;
    "created_at": number;
    "has_activity": boolean;
    "recommended": boolean;
}

export interface PersonalDriveSetupState {
    "status": string;
    "active_channel_id": string;
}

/**
 * PhotoBackupAsset is the native/frontend handoff shape for one discovered
 * photo-library or watched-folder item.
 */
export interface PhotoBackupAsset {
    "id": string;
    "version": string;
    "name": string;
    "media_type": string;
    "resource_id": string;
    "modified_at": number;

    /**
     * CreatedAt is the capture time in Unix milliseconds, or 0 when the host
     * does not know it. Editing a photo moves ModifiedAt; this stays put.
     */
    "created_at": number;
    "size": number;
}

export interface PhotoBackupCapabilities {
    "wifi_only": PhotoBackupCapability;
    "access": {"status": string, "detail": string};
}

export interface PhotoBackupCapability {
    "supported": boolean;
    "label": string;
    "detail": string;
}

export interface PhotoBackupPolicy {
    "wifi": boolean;
    "observed_at": number;
}

export interface PhotoBackupSettings {
    "enabled": boolean;
    "photos": boolean;
    "videos": boolean;
    "future_only": boolean;
    "wifi_only": boolean;
    "destination_parent_id": string;
    "encrypt": boolean;
}

export interface PhotoBackupSource {
    "id": string;
    "kind": string;
    "name": string;
    "root": string;
    "enabled": boolean;
    "added_at": number;
}

export interface PhotoBackupState {
    "settings": PhotoBackupSettings;
    "sources": PhotoBackupSource[] | null;
    "status": PhotoBackupStatus;
    "platform": string;
    "capabilities": PhotoBackupCapabilities;
    "destination": {"id": string, "title": string, "kind": string};
    "manual_paused": boolean;
    "encryption_required": boolean;
}

export interface PhotoBackupStatus {
    "current_file": string;
    "current_file_bytes_done": number;
    "current_file_bytes_total": number;
    "current_file_percent": number;
    "phase": string;
    "pending": number;
    "uploading": number;
    "complete": number;
    "failed": number;
    "paused"?: number;
    "bytes_done": number;
    "bytes_total": number;
    "message": string;
}

export interface PreviewPayload {
    "data_base64": string;
    "mime_type": string;
}

/**
 * PreviewResult adds preview bytes to the common operation envelope.
 */
export interface PreviewResult {
    "result": OperationResult;
    "payload": PreviewPayload;
}

/**
 * SafeAreaInsets is how much of each screen edge the OS reserves for its own
 * chrome: the status bar and the gesture handle on a phone. Zero everywhere
 * else. Android reports device pixels and iOS reports points, so the caller
 * scales by the device pixel ratio; see ui/mobile/safe-area.ts.
 */
export interface SafeAreaInsets {
    "top": number;
    "bottom": number;
    "left": number;
    "right": number;
}

/**
 * SelfUser is a small projection of the logged-in Telegram user, shaped
 * for the frontend profile menu. Photo download is best-effort; an empty
 * PhotoBase64 means "no photo available" and the UI should fall back to
 * initials.
 */
export interface SelfUser {
    "user_id": number;
    "display_name": string;
    "username"?: string;
    "photo_base64"?: string;
}

export interface TDriveFile {
    "id": number;
    "name": string;
    "size": number;
    "access_hash": number;
    "date": number;
}

/**
 * UploadResult adds uploaded file data to the common operation envelope.
 */
export interface UploadResult {
    "result": OperationResult;
    "files": backend$0.FileMetaData[] | null;
}
