// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as backend$0 from "./backend/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as media$0 from "./backend/media/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as nativeplayer$0 from "./backend/nativeplayer/models.js";

/**
 * AppVersionInfo describes the running build for the About/Updates panel.
 */
export interface AppVersionInfo {
    "version": string;
    "os": string;
    "arch": string;
    "dev_build": boolean;
}

/**
 * ChannelInfo is the Wails-bound DTO for a drive listed in the sidebar.
 */
export interface ChannelInfo {
    "id": number;
    "title": string;

    /**
     * "personal" | "shared"
     */
    "kind": string;
    "is_active": boolean;
    "invite_link"?: string;
}

/**
 * DownloadResult adds the chosen destination to the common operation envelope.
 */
export interface DownloadResult {
    "result": OperationResult;
    "saved_path": string;
}

/**
 * EncryptionStatus is the snapshot the frontend uses for per-upload prompts
 * and for unlocking an encrypted personal-drive mount. Mounted writes always
 * follow the drive policy; they never expose a per-file encryption choice.
 */
export interface EncryptionStatus {
    /**
     * a personal channel is known
     */
    "available": boolean;

    /**
     * user has created an encryption password
     */
    "password_set": boolean;

    /**
     * master key is in process memory
     */
    "password_remembered": boolean;

    /**
     * optional plaintext password hint
     */
    "hint": string;
}

/**
 * JoinDriveResult distinguishes instant joins from approval-required requests.
 */
export interface JoinDriveResult {
    /**
     * "joined" | "pending"
     */
    "status": string;
    "channel"?: ChannelInfo | null;
    "pending"?: PendingJoinInfo | null;
}

/**
 * JoinRequestInfo is shown to admins for approval-required invite links.
 */
export interface JoinRequestInfo {
    "user_id": number;
    "display_name": string;
    "username"?: string;
    "requested_at": number;
    "about"?: string;
}

export interface MountDriveView {
    "id"?: number;
    "title"?: string;
    "kind"?: string;
}

/**
 * MountResult adds capability-free mount state to the common operation envelope.
 */
export interface MountResult {
    "result": OperationResult;
    "mount": MountView;
}

/**
 * MountView is the capability-free mount state exposed to the webview. The
 * private WebDAV endpoint never crosses the Go/Wails boundary.
 */
export interface MountView {
    "phase": string;
    "mounted": boolean;
    "mode"?: string;
    "write_state"?: string;
    "accepting_writes"?: boolean;
    "active_writes"?: number;
    "label"?: string;
    "location"?: string;
    "error"?: string;
    "drive"?: MountDriveView;
    "windows_drive"?: string;
}

export interface NativeMediaRange {
    "start": number;
    "end": number;
}

export interface NativeMediaResult {
    "token": string;
    "name": string;
    "thumbnail_url": string;
    "html_controls": boolean;
    "presentation": string;
    "initial_state"?: NativeMediaState | null;
    "info": media$0.LogicalFile;
}

export interface NativeMediaState {
    "token"?: string;
    "sequence": number;
    "status": nativeplayer$0.PlaybackStatus;
    "error"?: string;
    "eof": boolean;
    "paused": boolean;
    "current_time": number;
    "duration": number;
    "buffered": NativeMediaRange[] | null;
    "volume": number;
    "muted": boolean;
    "rate": number;
    "loading": boolean;
    "tracks": nativeplayer$0.Track[] | null;
}

/**
 * OperationError keeps a stable code separate from user-facing detail.
 * cause is retained for native callers and deliberately omitted from JSON.
 */
export interface OperationError {
    "code": OperationErrorCode;
    "message": string;
}

/**
 * Operation error codes are stable control-plane values exposed over Wails.
 * The accompanying message is display text and must never be used for branching.
 */
export type OperationErrorCode = string;

/**
 * OperationResult is the common Wails operation envelope.
 */
export interface OperationResult {
    "ok": boolean;
    "error"?: OperationError | null;
}

/**
 * PendingJoinInfo is a local record for approval-required invite links where
 * the current Telegram account has requested access but is not a member yet.
 */
export interface PendingJoinInfo {
    "invite_hash": string;
    "invite_link": string;
    "title": string;
    "requested_at": number;
    "last_checked_at": number;
    "status": string;
    "last_error": string;
}

/**
 * PersonalDriveCandidate is a channel the user may recover as their drive.
 * The ID is a decimal string: Telegram IDs exceed JavaScript's safe integer
 * range. Access hashes stay backend-only.
 */
export interface PersonalDriveCandidate {
    "id": string;
    "title": string;
    "created_at": number;
    "has_activity": boolean;
    "recommended": boolean;
}

export interface PersonalDriveSetupState {
    "status": string;
    "active_channel_id": string;
}

export interface PreviewPayload {
    "data_base64": string;
    "mime_type": string;
}

/**
 * PreviewResult adds preview bytes to the common operation envelope.
 */
export interface PreviewResult {
    "result": OperationResult;
    "payload": PreviewPayload;
}

/**
 * SelfUser is a small projection of the logged-in Telegram user, shaped
 * for the frontend profile menu. Photo download is best-effort; an empty
 * PhotoBase64 means "no photo available" and the UI should fall back to
 * initials.
 */
export interface SelfUser {
    "user_id": number;
    "display_name": string;
    "username"?: string;
    "photo_base64"?: string;
}

export interface TDriveFile {
    "id": number;
    "name": string;
    "size": number;
    "access_hash": number;
    "date": number;
}

/**
 * UploadResult adds uploaded file data to the common operation envelope.
 */
export interface UploadResult {
    "result": OperationResult;
    "files": backend$0.FileMetaData[] | null;
}
