// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * UpdateService owns the desktop release lifecycle: reporting what this build
 * is, asking GitHub whether there is a newer one, downloading it, swapping it
 * into place and restarting into it.
 * 
 * These methods sit on one type because they all read or drive a single phase
 * machine, and because every one of them is meaningless without it: a "dev"
 * build and every mobile build leave that machine nil, and each method here
 * then degrades to PhaseDisabled instead of pretending an update is possible.
 * Grouping them also keeps the one destructive step -- replacing the bundle the
 * process is running from -- next to the checks that decide whether there is
 * anything worth replacing it with.
 * 
 * The rollback cleanup that runs at startup is deliberately not a method the
 * frontend can call; see finishCleanup.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as updater$0 from "./backend/updater/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AppVersion returns the build identity shown in the Updates panel.
 */
export function AppVersion(): $CancellablePromise<$models.AppVersionInfo> {
    return $Call.ByID(105597029);
}

/**
 * CancelUpdateDownload aborts the in-flight download.
 */
export function CancelUpdateDownload(): $CancellablePromise<void> {
    return $Call.ByID(4270562823);
}

/**
 * CheckForUpdate contacts GitHub and returns the resulting state. Failures
 * are reported inside the state rather than as an error so the panel has a
 * single source of truth.
 */
export function CheckForUpdate(): $CancellablePromise<updater$0.State> {
    return $Call.ByID(654227894);
}

/**
 * DownloadUpdate starts fetching the available release in the background.
 */
export function DownloadUpdate(): $CancellablePromise<void> {
    return $Call.ByID(943505489);
}

/**
 * GetUpdateState returns the current updater snapshot for hydration.
 */
export function GetUpdateState(): $CancellablePromise<updater$0.State> {
    return $Call.ByID(4160282334);
}

/**
 * InstallUpdateAndRestart swaps the verified payload into place, launches the
 * new version and quits. Native players are closed first so their sidecar
 * binaries are not in use while the bundle is replaced; the regular shutdown
 * path ejects any mounted drive and releases the backend lock, which the new
 * instance waits for before it starts.
 */
export function InstallUpdateAndRestart(): $CancellablePromise<void> {
    return $Call.ByID(4049900970);
}

/**
 * OpenUpdatePage opens the newest release's GitHub page in the browser, or
 * the releases index when no newer release is known. The URL never comes
 * from the frontend.
 */
export function OpenUpdatePage(): $CancellablePromise<void> {
    return $Call.ByID(3242673546);
}
