// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface MediaItem {
    "msg_id": number;
    "date": number;
    "name": string;
    "size": number;
    "mime_type": string;
    "kind": string;
    "caption": string;
    "streamable": boolean;
    "block_reason"?: string;
    "telegram_url": string;
}

export interface MediaPage {
    "channel_id": number;
    "account_id": number;
    "generation": string;
    "items": MediaItem[] | null;
    "next_offset_id": number;
    "has_more": boolean;
}

export interface SourceInfo {
    "channel_id": number;
    "title": string;
    "username"?: string;
    "connected": boolean;
    "protected": boolean;
    "available": boolean;
    "account_id": number;
    "generation"?: string;
}
