// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LogicalFile is the media subsystem's canonical view of a projected file.
 * 
 * StoredSize is the total bytes stored in Telegram. For encrypted files that is
 * ciphertext size; PlaintextSize is the size exposed to the player. Encryption
 * spans the concatenated stored stream, so multipart encrypted files are still
 * decrypted as one logical stream.
 */
export interface LogicalFile {
    "channel_id": number;
    "file_id": number;
    "revision": number;
    "name": string;
    "stored_size": number;
    "plaintext_size": number;
    "encrypted": boolean;
    "encryption_version": number;
    "multipart": boolean;
    "segments": Segment[] | null;
}

export interface MediaStats {
    "playback": ThroughputStats;
    "thumbnails": ThroughputStats;
}

export interface OpenResult {
    "token": string;
    "url": string;
    "thumbnail_url": string;

    /**
     * HLSURL is set only for a container Apple platforms cannot open, such as
     * Matroska. It points at a playlist backed by an on-demand remux, and it is
     * empty for every file a player can take directly.
     */
    "hls_url": string;
    "name": string;
    "kind": StreamKind;
    "mime_type": string;
    "supports_range": boolean;
    "info": LogicalFile;
}

export interface PlaybackUpdate {
    "token": string;
    "current_time": number;
    "duration": number;

    /**
     * BufferAhead is the number of seconds the player has buffered ahead of the
     * playhead. The thumbnail scheduler uses it to steal slack: build aggressively
     * while the buffer is comfortable and yield to playback as it drains.
     */
    "buffer_ahead": number;
}

/**
 * Segment is one stored Telegram document body in a logical TDrive file.
 * 
 * For normal files there is exactly one segment and MsgID is the file's own
 * message id. For multipart files, MsgID is a part message id while FileID on
 * LogicalFile remains the manifest message id used by the UI.
 */
export interface Segment {
    "msg_id": number;
    "size": number;
}

export enum StreamKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StreamKindUnknown = "unknown",
    StreamKindVideo = "video",
    StreamKindAudio = "audio",
    StreamKindPDF = "pdf",
    StreamKindText = "text",
    StreamKindImage = "image",
};

export interface ThroughputStats {
    "bytes_per_second": number;
    "recent_flood_wait": boolean;
    "last_flood_wait_seconds": number;
}
