// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as backend$0 from "../../backend/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as galleryimage$0 from "../../backend/galleryimage/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as projection$0 from "../../backend/projection/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as file$0 from "../../backend/services/file/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ActiveChannelID(): $CancellablePromise<number> {
    return $Call.ByID(3365339820);
}

/**
 * AddPhotoBackupFolder opens the desktop directory dialog. Mobile does not
 * come through here: Android picks its folder in the native layer, because the
 * Storage Access Framework answers with a document tree rather than a path and
 * only the host can turn one into something enumerable. It then arrives as an
 * ordinary UpsertPhotoBackupSource of kind photoBackupDeviceFolderKind.
 */
export function AddPhotoBackupFolder(): $CancellablePromise<$models.PhotoBackupSource> {
    return $Call.ByID(225190247);
}

/**
 * CancelDownload cancels the active download.
 */
export function CancelDownload(): $CancellablePromise<void> {
    return $Call.ByID(4033939734);
}

/**
 * CancelResumableUpload abandons a job and removes only the remote parts that
 * the backend has verified belong to that job.
 */
export function CancelResumableUpload(jobID: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(3636457551, jobID);
}

/**
 * CancelUpload cancels the in-flight upload or import: in-flight sends abort and
 * the rest are skipped. The frontend marks the affected transfers canceled.
 */
export function CancelUpload(): $CancellablePromise<void> {
    return $Call.ByID(994047299);
}

/**
 * CancelUploadByID cancels one file of the running batch. Both cancels exist
 * because uploads run several at a time: a transfer row's × stops that one
 * file, while CancelUpload above is the deliberate "stop everything".
 */
export function CancelUploadByID(uploadID: number): $CancellablePromise<void> {
    return $Call.ByID(711843299, uploadID);
}

export function CheckLoginStatus(): $CancellablePromise<boolean> {
    return $Call.ByID(1805736091);
}

export function CheckSystemStatus(): $CancellablePromise<string> {
    return $Call.ByID(2310536583);
}

export function ClearGalleryCache(): $CancellablePromise<$models.GalleryStorage> {
    return $Call.ByID(1344318353);
}

export function CloseGalleryImages(token: string): $CancellablePromise<void> {
    return $Call.ByID(1230796400, token);
}

export function CreateFolder(foldername: string, parentID: string): $CancellablePromise<backend$0.Folder> {
    return $Call.ByID(4072853788, foldername, parentID);
}

export function DeleteFile(msgID: number): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(2969367385, msgID);
}

export function DeleteFolder(folderID: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(1711982483, folderID);
}

/**
 * DeleteFromTrashPermanently destroys one object's Telegram bodies for good.
 * This is the user's explicit instruction, so it does not wait for the object's
 * retention window; that window only ever gates the automatic sweep.
 */
export function DeleteFromTrashPermanently(objectID: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(954326616, objectID);
}

/**
 * DiscardResumableDownload removes the job and its private partial bytes.
 */
export function DiscardResumableDownload(channelID: number, jobID: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(754280266, channelID, jobID);
}

/**
 * DownloadFile downloads from the explicitly selected drive. The channel is an
 * argument rather than a late ActiveChannelID lookup because a queued frontend
 * transfer may begin after the user has switched drives.
 */
export function DownloadFile(channelID: number, msgID: number, TgMsgID: number, requestID: string): $CancellablePromise<$models.DownloadResult> {
    return $Call.ByID(2749076578, channelID, msgID, TgMsgID, requestID);
}

/**
 * DownloadFolder restores the selected projected folder beneath a destination
 * parent chosen once by the user. It shares the serialized/cancellable download
 * slot with single-file downloads, so the existing CancelDownload action stops
 * either transfer type.
 */
export function DownloadFolder(channelID: number, folderID: string, requestID: string): $CancellablePromise<$models.DownloadResult> {
    return $Call.ByID(911995584, channelID, folderID, requestID);
}

/**
 * EmptyTrash purges every entry. It stops at the first failure rather than
 * carrying on, so the trash the user sees afterwards is exactly what is left to
 * deal with instead of an arbitrary subset.
 */
export function EmptyTrash(): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(132778333);
}

export function EnqueuePhotoBackupAssets(sourceID: string, values: $models.PhotoBackupAsset[] | null): $CancellablePromise<number> {
    return $Call.ByID(1336452721, sourceID, values);
}

/**
 * GetAllFsMsgIDs lists the Telegram messages this drive already accounts for.
 * The root listing subtracts them from the channel's history to show what was
 * posted outside TDrive; a deleted file stays on the list, because its message
 * is still ours until the trash purges it.
 */
export function GetAllFsMsgIDs(): $CancellablePromise<number[] | null> {
    return $Call.ByID(670393433);
}

export function GetFileList(): $CancellablePromise<$models.TDriveFile[] | null> {
    return $Call.ByID(563907866);
}

export function GetFolderContents(parentID: string): $CancellablePromise<backend$0.FileSystem> {
    return $Call.ByID(86663918, parentID);
}

export function GetFolderSize(folderID: string): $CancellablePromise<number> {
    return $Call.ByID(4043922613, folderID);
}

export function GetFolderStats(parentID: string): $CancellablePromise<projection$0.FolderStats[] | null> {
    return $Call.ByID(2849945911, parentID);
}

export function GetGalleryStorage(): $CancellablePromise<$models.GalleryStorage> {
    return $Call.ByID(4199653987);
}

/**
 * GetMediaFolderTimeline is the scoped counterpart of GetMediaTimelineSummary.
 * A folder has no anchor index: it is small enough to seek by paging, so this
 * carries only the month buckets the grid lays out against.
 */
export function GetMediaFolderTimeline(folderID: string): $CancellablePromise<projection$0.GalleryTimeline> {
    return $Call.ByID(79813515, folderID);
}

export function GetMediaNeighbors(msgID: number, before: number, after: number, generation: string): $CancellablePromise<$models.GalleryPage> {
    return $Call.ByID(1294378703, msgID, before, after, generation);
}

/**
 * GetMediaTimeline returns only compact layout metadata and sparse page keys.
 * A cursor is tied to the account database, active drive, and projection epoch.
 */
export function GetMediaTimeline(): $CancellablePromise<projection$0.GalleryTimeline> {
    return $Call.ByID(1693441887);
}

export function GetMediaTimelineAnchors(generation: string): $CancellablePromise<projection$0.GalleryTimeline> {
    return $Call.ByID(1179161999, generation);
}

export function GetMediaTimelineSummary(): $CancellablePromise<projection$0.GalleryTimeline> {
    return $Call.ByID(3648692089);
}

export function GetPhotoBackupState(): $CancellablePromise<$models.PhotoBackupState> {
    return $Call.ByID(3024515271);
}

export function GetStorageUsed(): $CancellablePromise<number> {
    return $Call.ByID(1501433628);
}

/**
 * ImportPaths recreates the folder structure of the selected paths under
 * parentID and uploads their files. Archives are extracted when extractArchives
 * is set, otherwise uploaded as-is. Progress flows through aggregate import_*
 * events.
 */
export function ImportPaths(paths: string[] | null, parentID: string, encrypt: boolean, extractArchives: boolean): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(3650510347, paths, parentID, encrypt, extractArchives);
}

export function ListMediaFolderPage(folderID: string, cursor: string, limit: number): $CancellablePromise<$models.GalleryPage> {
    return $Call.ByID(636232343, folderID, cursor, limit);
}

/**
 * ListMediaFolders returns the album grid: every folder that directly holds
 * media, newest first, with its count and the newest item as a cover.
 */
export function ListMediaFolders(): $CancellablePromise<projection$0.GalleryFolder[] | null> {
    return $Call.ByID(1769198365);
}

export function ListMediaPage(cursor: string, limit: number): $CancellablePromise<$models.GalleryPage> {
    return $Call.ByID(3569251139, cursor, limit);
}

/**
 * ListResumableDownloads returns only jobs for the requested drive. The file
 * service also scopes its journal to the signed-in account.
 */
export function ListResumableDownloads(channelID: number): $CancellablePromise<$models.ResumableDownloadsResult> {
    return $Call.ByID(1931809929, channelID);
}

/**
 * ListResumableUploads returns backend-confirmed multipart upload checkpoints
 * for the selected drive. The frontend's transfer history is not a receipt.
 */
export function ListResumableUploads(): $CancellablePromise<file$0.ResumableUpload[] | null> {
    return $Call.ByID(4229695062);
}

/**
 * ListTrash returns everything still restorable, most recently deleted first.
 * 
 * It is a pure read: purging is the background sweep's job (trash_sweep.go)
 * precisely so that opening the Trash panel can never block on Telegram. An
 * entry whose window has closed but that the sweep has not reached yet is still
 * listed, and is still restorable, which is the lenient side to err on.
 */
export function ListTrash(): $CancellablePromise<$models.TrashEntry[] | null> {
    return $Call.ByID(3072815278);
}

export function LocateMedia(msgID: number, generation: string): $CancellablePromise<projection$0.GalleryLocation> {
    return $Call.ByID(2643144062, msgID, generation);
}

export function LoginPhoneNumber(phoneNumber: string): $CancellablePromise<void> {
    return $Call.ByID(508447178, phoneNumber);
}

/**
 * Logout signs the user out of TDrive.
 * 
 * Soft mode drops only the local gotd session token, so the same Telegram
 * account can re-login quickly without re-projecting their drives. The
 * session stays valid server-side until Telegram itself expires it.
 * 
 * Full mode revokes the session on Telegram's side via auth.logOut and then
 * deletes all user-scoped files on disk (session, personal channel id,
 * SQLite cache, API credentials).
 * 
 * In both cases the app quits at the end. We rely on the next launch to
 * rebuild syncEngine, backfillRunner, and the DB handle from a clean slate
 * instead of tearing them down mid-process while goroutines may still be
 * touching backend.DB.
 */
export function Logout(mode: string): $CancellablePromise<void> {
    return $Call.ByID(4220834258, mode);
}

/**
 * Me resolves the logged-in Telegram user and a small base64-encoded
 * avatar photo. The result is cached by the user service for the lifetime
 * of the process; logout clears it.
 */
export function Me(): $CancellablePromise<$models.SelfUser> {
    return $Call.ByID(2964945090);
}

/**
 * MountDrive attaches the active drive without changing it. The controller
 * pins this immutable drive record until the user disconnects it.
 */
export function MountDrive(): $CancellablePromise<$models.MountResult> {
    return $Call.ByID(2716733755);
}

/**
 * MountDrives attaches an explicit selection inside one TDrive volume. The
 * client supplies IDs only; titles, kinds, and encryption state are resolved
 * from the authoritative local projection before the controller is called.
 */
export function MountDrives(channelIDs: number[] | null): $CancellablePromise<$models.MountResult> {
    return $Call.ByID(835007576, channelIDs);
}

export function MountStatus(): $CancellablePromise<$models.MountView> {
    return $Call.ByID(295477771);
}

export function MoveFile(msgID: number, newParentID: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(3630349151, msgID, newParentID);
}

export function MoveFolder(folderID: string, newParentID: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(3355138329, folderID, newParentID);
}

export function MsgToTdriveSystem(msgID: number, name: string, size: number, parentID: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(818834345, msgID, name, size, parentID);
}

/**
 * MyUserID returns the logged-in Telegram user id (cached after first
 * resolution). The frontend uses it to gate owner-only actions on shared
 * drives. Returns an error if Telegram resolution fails — caller should
 * default-deny the gated actions in that case.
 */
export function MyUserID(): $CancellablePromise<number> {
    return $Call.ByID(3440114372);
}

/**
 * OpenGalleryImages creates one capability for a gallery and its viewer. The
 * expected channel prevents a late bridge response from opening a new drive's
 * images under an old UI. Individual binary requests carry their own cancel.
 */
export function OpenGalleryImages(channelID: number): $CancellablePromise<galleryimage$0.OpenResult> {
    return $Call.ByID(419901100, channelID);
}

export function OpenMountedDrive(): $CancellablePromise<void> {
    return $Call.ByID(3666648536);
}

export function PausePhotoBackup(): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(252730664);
}

/**
 * PauseResumableDownload retains verified bytes for a later attempt.
 */
export function PauseResumableDownload(channelID: number, jobID: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(2768883090, channelID, jobID);
}

/**
 * PauseResumableUpload stops the current attempt while retaining its durable
 * Telegram message checkpoints.
 */
export function PauseResumableUpload(jobID: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(1407608695, jobID);
}

/**
 * PlanImport scans the selected paths and returns the counts shown in the
 * import dialog (files, folders, total size, archives, oversize-skipped). It
 * mutates nothing.
 */
export function PlanImport(paths: string[] | null, encrypt: boolean, extractArchives: boolean): $CancellablePromise<file$0.ImportPlan> {
    return $Call.ByID(1091920750, paths, encrypt, extractArchives);
}

export function PreviewFile(msgID: number): $CancellablePromise<$models.PreviewResult> {
    return $Call.ByID(1265681854, msgID);
}

export function PreviewThumbnail(msgID: number): $CancellablePromise<$models.PreviewResult> {
    return $Call.ByID(2557467908, msgID);
}

/**
 * RebuildProjection wipes and replays the local projection for a channel
 * from the channel's replay_log. Hidden Wails method for debug/recovery.
 */
export function RebuildProjection(channelID: number): $CancellablePromise<void> {
    return $Call.ByID(3751182286, channelID);
}

export function RemovePhotoBackupSource(id: string): $CancellablePromise<void> {
    return $Call.ByID(818045651, id);
}

export function RenameFile(msgID: number, newName: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(439534888, msgID, newName);
}

export function RenameFolder(folderID: string, newName: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(751076414, folderID, newName);
}

export function ResolvePhotoBackupResource(token: string, path: string, errorMessage: string): $CancellablePromise<void> {
    return $Call.ByID(1166114682, token, path, errorMessage);
}

/**
 * ResolveUsernames maps Telegram user IDs to display names. Used by the
 * frontend uploader-chip cache.
 */
export function ResolveUsernames(userIDs: number[] | null): $CancellablePromise<{ [_ in string]?: string } | null> {
    return $Call.ByID(2470544089, userIDs);
}

/**
 * RestoreFromTrash puts one object back. It lands under its original parent, or
 * under the drive root if that parent is gone, and takes a numbered name if the
 * original is occupied -- never refusing outright, because a refusal would
 * leave the user with no way to recover the object at all.
 */
export function RestoreFromTrash(objectID: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(2289341816, objectID);
}

/**
 * ResumeDownload continues the pinned source and destination of an existing job.
 * The caller's current drive never retargets the transfer.
 */
export function ResumeDownload(channelID: number, jobID: string, requestID: string): $CancellablePromise<$models.DownloadResult> {
    return $Call.ByID(2308165947, channelID, jobID, requestID);
}

export function ResumePhotoBackup(): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(4024796299);
}

/**
 * ResumeResumableUpload continues one paused multipart upload. An empty source
 * path reuses the original path; a selected replacement is verified by the
 * service before it can contribute bytes to an existing upload.
 */
export function ResumeResumableUpload(jobID: string, sourcePath: string): $CancellablePromise<$models.UploadResult> {
    return $Call.ByID(1946634256, jobID, sourcePath);
}

export function RetryPhotoBackup(): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(902368056);
}

/**
 * The backup controls answer with the common operation envelope so the
 * frontend can branch on a stable code — a locked vault opens the password
 * prompt, anything else is shown in the backend's own words — rather than
 * sniffing display text out of a wrapped Go error.
 */
export function RunPhotoBackup(): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(170834557);
}

export function SavePhotoBackupSettings(value: $models.PhotoBackupSettings): $CancellablePromise<$models.PhotoBackupState> {
    return $Call.ByID(1192491680, value);
}

export function SaveSetup(apiId: number, apiHash: string): $CancellablePromise<string> {
    return $Call.ByID(2028034986, apiId, apiHash);
}

export function Search(query: string, limit: number): $CancellablePromise<backend$0.SearchResult[] | null> {
    return $Call.ByID(2835473520, query, limit);
}

export function SelectFiles(): $CancellablePromise<string[] | null> {
    return $Call.ByID(1881825507);
}

/**
 * SelectFolder opens a directory picker and returns the chosen folder path
 * (empty if the user cancels). Folder import walks it on the Go side.
 */
export function SelectFolder(): $CancellablePromise<string> {
    return $Call.ByID(3788887392);
}

export function SendHint(hint: string): $CancellablePromise<void> {
    return $Call.ByID(3322236671, hint);
}

export function SetActiveChannel(channelID: number): $CancellablePromise<void> {
    return $Call.ByID(1062144257, channelID);
}

/**
 * SetFileDropEnabled toggles whether the native OS file-drop handler (wired
 * up once in run.go against the window) forwards drops to the frontend. The
 * frontend turns it off for the duration of an internal drag-to-move: on
 * macOS the webview's native drop destination otherwise intercepts the
 * in-app HTML5 drag, which breaks the move and pops the upload dialog.
 */
export function SetFileDropEnabled(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(316244124, enabled);
}

/**
 * SetPhotoBackupBackgroundLease records a lease only after the native host has
 * acquired its execution grant. Repeated calls cannot extend Android's
 * cumulative dataSync budget.
 */
export function SetPhotoBackupBackgroundLease(active: boolean): $CancellablePromise<void> {
    return $Call.ByID(385592700, active);
}

export function SetPhotoBackupPolicy(policy: $models.PhotoBackupPolicy): $CancellablePromise<void> {
    return $Call.ByID(1685800152, policy);
}

/**
 * ShareFile opens the platform share sheet for a file TDrive wrote itself.
 * Anything outside the folders it owns is refused so the webview cannot hand
 * arbitrary files to other apps. Desktop reports unsupported.
 */
export function ShareFile(path: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(820449561, path);
}

export function SubmitCode(code: string): $CancellablePromise<void> {
    return $Call.ByID(2343070425, code);
}

export function SubmitPassword(password: string): $CancellablePromise<void> {
    return $Call.ByID(2629996429, password);
}

/**
 * SyncChannel triggers an incremental sync for the given channel. Wails-bound
 * for the future "Refresh" UI button and for debug.
 */
export function SyncChannel(channelID: number): $CancellablePromise<void> {
    return $Call.ByID(2067229710, channelID);
}

export function UnmountDrive(): $CancellablePromise<$models.MountView> {
    return $Call.ByID(1851039664);
}

/**
 * UploadToDriveFS uploads the selected batch. Encryption is chosen per batch;
 * encrypted uploads require an already unlocked vault.
 */
export function UploadToDriveFS(filePaths: string[] | null, parentIDs: string[] | null, encrypt: boolean): $CancellablePromise<$models.UploadResult> {
    return $Call.ByID(4020749391, filePaths, parentIDs, encrypt);
}

export function UpsertPhotoBackupSource(value: $models.PhotoBackupSource): $CancellablePromise<$models.PhotoBackupSource> {
    return $Call.ByID(1576926270, value);
}
