// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Phase is where the updater is in the check → download → install lifecycle.
 * Errors do not get a phase of their own: a failed step reports its message
 * in State.Error while the phase stays wherever the payload actually is, so a
 * verified download survives a flaky re-check.
 */
export enum Phase {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * nothing checked yet this session
     */
    PhaseIdle = "idle",

    /**
     * development build, updater off
     */
    PhaseDisabled = "disabled",

    /**
     * talking to GitHub
     */
    PhaseChecking = "checking",

    /**
     * newest release is running
     */
    PhaseUpToDate = "up_to_date",

    /**
     * newer release known, not on disk
     */
    PhaseAvailable = "available",

    /**
     * payload streaming into the cache
     */
    PhaseDownloading = "downloading",

    /**
     * verified payload on disk
     */
    PhaseReady = "ready",

    /**
     * swapping files
     */
    PhaseInstalling = "installing",

    /**
     * swap done, restart pending
     */
    PhaseInstalled = "installed",
};

/**
 * ReleaseInfo is the user-facing summary of the newest release.
 */
export interface ReleaseInfo {
    "version": string;
    "tag": string;
    "page_url": string;
    "published_at": string;
    "asset_name": string;
    "asset_size": number;
}

/**
 * State is the snapshot the frontend renders. Every transition is delivered
 * through Options.OnChange in order, and Service.State returns the same shape
 * for hydration.
 */
export interface State {
    "phase": Phase;
    "current_version": string;
    "latest": ReleaseInfo | null;
    "installable": boolean;
    "install_hint": string;
    "downloaded_bytes": number;
    "total_bytes": number;

    /**
     * unix milliseconds, 0 = never
     */
    "checked_at": number;
    "error": string;

    /**
     * "check" | "download" | "install"
     */
    "error_stage": string;
}
