// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ImportPlan is the summary shown in the import dialog before confirming.
 */
export interface ImportPlan {
    /**
     * files that would upload (excludes oversize)
     */
    "files": number;

    /**
     * folders that would be created
     */
    "folders": number;

    /**
     * total plaintext bytes of the uploadable files
     */
    "bytes": number;

    /**
     * files skipped for exceeding the per-file limit
     */
    "oversize": number;

    /**
     * archive items in the selection
     */
    "archives": number;

    /**
     * generated/cache roots pruned from the selection
     */
    "ignored": number;

    /**
     * active per-file limit, for messaging
     */
    "maxBytes": number;

    /**
     * maximum files + folders in one import
     */
    "maxItems": number;

    /**
     * LimitExceeded is set after counting one item beyond MaxItems. Planning
     * stops there so an accidental huge tree cannot consume unbounded memory.
     */
    "limitExceeded": boolean;
    "errorCount": number;

    /**
     * items that could not be scanned
     */
    "errors": string[] | null;
}

/**
 * ResumableUpload is the public, path-free view of a local multipart job.
 * ConfirmedBytes counts durable part receipts, not bytes in the current send.
 */
export interface ResumableUpload {
    "job_id": string;
    "channel_id": number;
    "name": string;
    "parent_id": string;
    "size": number;
    "stored_size": number;
    "confirmed_bytes": number;
    "status": string;
    "error": string;
    "upload_id"?: number | null;
}
