// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckLoginStatus():Promise<boolean>;

export function DownloadFile(arg1:number):Promise<string>;

export function GetCodech():Promise<any>;

export function GetFileList():Promise<Array<main.TDriveFile>>;

export function GetPassch():Promise<any>;

export function Greet(arg1:string):Promise<string>;

export function InitDrive():Promise<string>;

export function LoginPhoneNumber(arg1:string):Promise<void>;

export function SelectFile():Promise<string>;

export function SendHint(arg1:string):Promise<void>;

export function SumbitCode(arg1:string):Promise<void>;

export function SumbitPassword(arg1:string):Promise<void>;

export function UploadToTelegram(arg1:string):Promise<string>;
