// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';
import {main} from '../models';

export function CancelDownload(arg1:number):Promise<string>;

export function CancelUpload(arg1:number):Promise<string>;

export function CheckLoginStatus():Promise<boolean>;

export function CheckSystemStatus():Promise<string>;

export function CreateFolder(arg1:string,arg2:string):Promise<backend.Folder>;

export function DeleteFile(arg1:number):Promise<string>;

export function DeleteFolder(arg1:string):Promise<string>;

export function DownloadFile(arg1:number,arg2:number):Promise<main.DownloadResult>;

export function GetAllFsMsgIDs():Promise<Array<number>>;

export function GetCodech():Promise<any>;

export function GetFileList():Promise<Array<main.TDriveFile>>;

export function GetFolderContents(arg1:string):Promise<backend.FileSystem>;

export function GetFolderSize(arg1:string):Promise<number>;

export function GetPassch():Promise<any>;

export function GetStorageUsed():Promise<number>;

export function Greet(arg1:string):Promise<string>;

export function InitDrive():Promise<string>;

export function LoginPhoneNumber(arg1:string):Promise<void>;

export function MoveFile(arg1:number,arg2:string):Promise<string>;

export function MoveFolder(arg1:string,arg2:string):Promise<string>;

export function MsgToTdriveSystem(arg1:number,arg2:string,arg3:number,arg4:string):Promise<string>;

export function PreviewFile(arg1:number):Promise<main.PreviewPayload>;

export function PreviewThumbnail(arg1:number):Promise<main.PreviewPayload>;

export function RenameFile(arg1:number,arg2:string):Promise<string>;

export function RenameFolder(arg1:string,arg2:string):Promise<string>;

export function SaveSetup(arg1:number,arg2:string):Promise<string>;

export function Search(arg1:string,arg2:number):Promise<Array<backend.SearchResult>>;

export function SelectFiles():Promise<Array<string>>;

export function SendHint(arg1:string):Promise<void>;

export function SumbitCode(arg1:string):Promise<void>;

export function SumbitPassword(arg1:string):Promise<void>;

export function UploadToDriveFS(arg1:Array<string>,arg2:Array<string>):Promise<Array<backend.FileMetaData>>;
