// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {backend} from '../models';
import {media} from '../models';
import {nativeplayer} from '../models';
import {file} from '../models';

export function ActiveChannelID():Promise<number>;

export function ApproveJoinRequest(arg1:number,arg2:number):Promise<void>;

export function CancelDownload():Promise<void>;

export function CancelUpload():Promise<void>;

export function ChangeEncryptionPassword(arg1:string,arg2:string,arg3:string):Promise<void>;

export function CheckLoginStatus():Promise<boolean>;

export function CheckPendingJoin(arg1:string):Promise<main.JoinDriveResult>;

export function CheckSystemStatus():Promise<string>;

export function CloseMedia(arg1:string):Promise<void>;

export function CloseNativeMedia(arg1:string):Promise<void>;

export function CreateEncryptionPassword(arg1:string,arg2:string):Promise<void>;

export function CreateFolder(arg1:string,arg2:string):Promise<backend.Folder>;

export function CreateSharedDrive(arg1:string,arg2:boolean):Promise<main.ChannelInfo>;

export function DeleteFile(arg1:number):Promise<string>;

export function DeleteFolder(arg1:string):Promise<string>;

export function DownloadFile(arg1:number,arg2:number):Promise<main.DownloadResult>;

export function EncryptionStatus():Promise<main.EncryptionStatus>;

export function GetAllFsMsgIDs():Promise<Array<number>>;

export function GetApprovalInviteLink(arg1:number):Promise<string>;

export function GetCodech():Promise<any>;

export function GetFileList():Promise<Array<main.TDriveFile>>;

export function GetFolderContents(arg1:string):Promise<backend.FileSystem>;

export function GetFolderSize(arg1:string):Promise<number>;

export function GetFolderSizes(arg1:string):Promise<Record<string, number>>;

export function GetInviteLink(arg1:number):Promise<string>;

export function GetMediaStats(arg1:string):Promise<media.MediaStats>;

export function GetPassch():Promise<any>;

export function GetStorageUsed():Promise<number>;

export function ImportPaths(arg1:Array<string>,arg2:string,arg3:boolean,arg4:boolean):Promise<void>;

export function InitDrive():Promise<string>;

export function JoinSharedDrive(arg1:string):Promise<main.JoinDriveResult>;

export function LeaveSharedDrive(arg1:number):Promise<void>;

export function ListChannels():Promise<Array<main.ChannelInfo>>;

export function ListJoinRequests(arg1:number):Promise<Array<main.JoinRequestInfo>>;

export function ListMedia():Promise<Array<backend.FileMetaData>>;

export function ListPendingJoins():Promise<Array<main.PendingJoinInfo>>;

export function LoginPhoneNumber(arg1:string):Promise<void>;

export function Logout(arg1:string):Promise<void>;

export function Me():Promise<main.SelfUser>;

export function MoveFile(arg1:number,arg2:string):Promise<string>;

export function MoveFolder(arg1:string,arg2:string):Promise<string>;

export function MsgToTdriveSystem(arg1:number,arg2:string,arg3:number,arg4:string):Promise<string>;

export function MyUserID():Promise<number>;

export function NativeMediaCommand(arg1:string,arg2:Array<string>):Promise<void>;

export function OpenMedia(arg1:number):Promise<media.OpenResult>;

export function OpenNativeMedia(arg1:number,arg2:nativeplayer.Rect):Promise<main.NativeMediaResult>;

export function PlanImport(arg1:Array<string>,arg2:boolean,arg3:boolean):Promise<file.ImportPlan>;

export function PreviewFile(arg1:number):Promise<main.PreviewPayload>;

export function PreviewThumbnail(arg1:number):Promise<main.PreviewPayload>;

export function RebuildProjection(arg1:number):Promise<void>;

export function RejectJoinRequest(arg1:number,arg2:number):Promise<void>;

export function RemovePendingJoin(arg1:string):Promise<void>;

export function RenameFile(arg1:number,arg2:string):Promise<string>;

export function RenameFolder(arg1:string,arg2:string):Promise<string>;

export function ResizeNativeMedia(arg1:string,arg2:nativeplayer.Rect):Promise<void>;

export function ResolveUsernames(arg1:Array<number>):Promise<Record<string, string>>;

export function SaveSetup(arg1:number,arg2:string):Promise<string>;

export function Search(arg1:string,arg2:number):Promise<Array<backend.SearchResult>>;

export function SelectFiles():Promise<Array<string>>;

export function SelectFolder():Promise<string>;

export function SendHint(arg1:string):Promise<void>;

export function SetActiveChannel(arg1:number):Promise<void>;

export function SetFileDropEnabled(arg1:boolean):Promise<void>;

export function SumbitCode(arg1:string):Promise<void>;

export function SumbitPassword(arg1:string):Promise<void>;

export function SyncChannel(arg1:number):Promise<void>;

export function Thumbnail(arg1:number):Promise<main.PreviewPayload>;

export function UpdateMediaPlayback(arg1:media.PlaybackUpdate):Promise<void>;

export function UploadToDriveFS(arg1:Array<string>,arg2:Array<string>,arg3:boolean):Promise<Array<backend.FileMetaData>>;

export function UseEncryptionPassword(arg1:string):Promise<void>;
