// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckLoginStatus() {
  return window['go']['main']['App']['CheckLoginStatus']();
}

export function CheckSystemStatus() {
  return window['go']['main']['App']['CheckSystemStatus']();
}

export function DeleteFile(arg1) {
  return window['go']['main']['App']['DeleteFile'](arg1);
}

export function DownloadFile(arg1) {
  return window['go']['main']['App']['DownloadFile'](arg1);
}

export function GetCodech() {
  return window['go']['main']['App']['GetCodech']();
}

export function GetFileList() {
  return window['go']['main']['App']['GetFileList']();
}

export function GetPassch() {
  return window['go']['main']['App']['GetPassch']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function InitDrive() {
  return window['go']['main']['App']['InitDrive']();
}

export function LoginPhoneNumber(arg1) {
  return window['go']['main']['App']['LoginPhoneNumber'](arg1);
}

export function SaveSetup(arg1, arg2) {
  return window['go']['main']['App']['SaveSetup'](arg1, arg2);
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function SendHint(arg1) {
  return window['go']['main']['App']['SendHint'](arg1);
}

export function SumbitCode(arg1) {
  return window['go']['main']['App']['SumbitCode'](arg1);
}

export function SumbitPassword(arg1) {
  return window['go']['main']['App']['SumbitPassword'](arg1);
}

export function UploadToTelegram(arg1) {
  return window['go']['main']['App']['UploadToTelegram'](arg1);
}
