// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckLoginStatus() {
  return window['go']['main']['App']['CheckLoginStatus']();
}

export function CheckSystemStatus() {
  return window['go']['main']['App']['CheckSystemStatus']();
}

export function CreateFolder(arg1, arg2) {
  return window['go']['main']['App']['CreateFolder'](arg1, arg2);
}

export function DeleteFile(arg1) {
  return window['go']['main']['App']['DeleteFile'](arg1);
}

export function DeleteFolder(arg1) {
  return window['go']['main']['App']['DeleteFolder'](arg1);
}

export function DownloadFile(arg1, arg2) {
  return window['go']['main']['App']['DownloadFile'](arg1, arg2);
}

export function GetAllFsMsgIDs() {
  return window['go']['main']['App']['GetAllFsMsgIDs']();
}

export function GetCodech() {
  return window['go']['main']['App']['GetCodech']();
}

export function GetFileList() {
  return window['go']['main']['App']['GetFileList']();
}

export function GetFolderContents(arg1) {
  return window['go']['main']['App']['GetFolderContents'](arg1);
}

export function GetFolderSize(arg1) {
  return window['go']['main']['App']['GetFolderSize'](arg1);
}

export function GetPassch() {
  return window['go']['main']['App']['GetPassch']();
}

export function GetStorageUsed() {
  return window['go']['main']['App']['GetStorageUsed']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function InitDrive() {
  return window['go']['main']['App']['InitDrive']();
}

export function LoginPhoneNumber(arg1) {
  return window['go']['main']['App']['LoginPhoneNumber'](arg1);
}

export function MoveFile(arg1, arg2) {
  return window['go']['main']['App']['MoveFile'](arg1, arg2);
}

export function MoveFolder(arg1, arg2) {
  return window['go']['main']['App']['MoveFolder'](arg1, arg2);
}

export function MsgToTdriveSystem(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['MsgToTdriveSystem'](arg1, arg2, arg3, arg4);
}

export function RenameFile(arg1, arg2) {
  return window['go']['main']['App']['RenameFile'](arg1, arg2);
}

export function RenameFolder(arg1, arg2) {
  return window['go']['main']['App']['RenameFolder'](arg1, arg2);
}

export function SaveSetup(arg1, arg2) {
  return window['go']['main']['App']['SaveSetup'](arg1, arg2);
}

export function Search(arg1, arg2) {
  return window['go']['main']['App']['Search'](arg1, arg2);
}

export function SelectFiles() {
  return window['go']['main']['App']['SelectFiles']();
}

export function SendHint(arg1) {
  return window['go']['main']['App']['SendHint'](arg1);
}

export function SumbitCode(arg1) {
  return window['go']['main']['App']['SumbitCode'](arg1);
}

export function SumbitPassword(arg1) {
  return window['go']['main']['App']['SumbitPassword'](arg1);
}

export function UploadToDriveFS(arg1, arg2) {
  return window['go']['main']['App']['UploadToDriveFS'](arg1, arg2);
}
